services:
  - type: web
    name: api-recetas-ia-backend
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 4000
      - key: DATABASE_URL
        sync: false # Set in Render dashboard
      - key: groq_api_key
        sync: false # Set in Render dashboard
      - key: BACKEND_URL
        sync: false # Set in Render dashboard
    autoDeploy: true
    rootDir: .
  - type: web
    name: api-recetas-ia-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    autoDeploy: true
    rootDir: .
  - type: web
    name: api-recetas-ia-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    autoDeploy: true
    rootDir: .
